/*
 * Solanabeach Backend API
 *
 * Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: andrej@vgng.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountSwapInstruction {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "blocknumber", skip_serializing_if = "Option::is_none")]
    pub blocknumber: Option<i32>,
    #[serde(rename = "transactionhash", skip_serializing_if = "Option::is_none")]
    pub transactionhash: Option<String>,
    #[serde(rename = "tokenswap", skip_serializing_if = "Option::is_none")]
    pub tokenswap: Option<Box<crate::models::AccountSwapInstructionTokenswap>>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::Address>>,
    #[serde(rename = "instruction", skip_serializing_if = "Option::is_none")]
    pub instruction: Option<String>,
    #[serde(rename = "instructiondata", skip_serializing_if = "Option::is_none")]
    pub instructiondata: Option<serde_json::Value>,
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    #[serde(rename = "txindex", skip_serializing_if = "Option::is_none")]
    pub txindex: Option<i32>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Box<crate::models::Timestamp>>,
    #[serde(rename = "ondemand", skip_serializing_if = "Option::is_none")]
    pub ondemand: Option<bool>,
}

impl AccountSwapInstruction {
    pub fn new() -> AccountSwapInstruction {
        AccountSwapInstruction {
            id: None,
            blocknumber: None,
            transactionhash: None,
            tokenswap: None,
            owner: None,
            instruction: None,
            instructiondata: None,
            valid: None,
            index: None,
            txindex: None,
            timestamp: None,
            ondemand: None,
        }
    }
}


